package kr.seremc.nickname.velocity;

import com.velocitypowered.api.command.*;
import com.velocitypowered.api.proxy.*;
import kr.seremc.nickname.api.*;
import net.kyori.adventure.text.Component;
import org.slf4j.Logger;
import java.util.*;
import java.util.concurrent.*;

final class VelocityCommands implements SimpleCommand {
 private final VelocityNicknamePlugin plugin;private final ProxyServer proxy;private final NicknameService names;private final Logger logger;private boolean admin;
 VelocityCommands(VelocityNicknamePlugin plugin,ProxyServer proxy,NicknameService names,Logger logger){this.plugin=plugin;this.proxy=proxy;this.names=names;this.logger=logger;}
 void register(){var userMeta=proxy.getCommandManager().metaBuilder("nickname").aliases("nick","닉네임").plugin(plugin).build();proxy.getCommandManager().register(userMeta,this);VelocityCommands adminCommand=new VelocityCommands(plugin,proxy,names,logger);adminCommand.admin=true;var adminMeta=proxy.getCommandManager().metaBuilder("nickadmin").aliases("닉관리").plugin(plugin).build();proxy.getCommandManager().register(adminMeta,adminCommand);}
 @Override public void execute(Invocation invocation){try{if(admin)admin(invocation);else user(invocation);}catch(IllegalArgumentException e){tell(invocation.source(),e.getMessage());}}
 private void user(Invocation in){String[] a=in.arguments();if(a.length==0){tell(in.source(),"/닉네임 조회 [닉네임|@계정명|UUID] | /닉네임 변경 <새이름>");return;}if(eq(a[0],"조회","lookup")){if(a.length==1&&in.source() instanceof Player p)finish(in.source(),names.findById(p.getUniqueId()).thenApply(v->v.orElseThrow(()->new IllegalArgumentException("프로필이 없습니다."))),profile->show(in.source(),profile));else if(a.length==2)finish(in.source(),resolve(a[1]),profile->show(in.source(),profile));else throw new IllegalArgumentException("/닉네임 조회 [대상]");return;}if(eq(a[0],"변경","change")){if(!(in.source() instanceof Player p))throw new IllegalArgumentException("플레이어만 사용할 수 있습니다.");if(a.length!=2)throw new IllegalArgumentException("/닉네임 변경 <새이름>");plugin.requestTicketUse(p,a[1]);tell(p,"변경권을 확인하고 있습니다.");return;}throw new IllegalArgumentException("/닉네임 조회 또는 /닉네임 변경을 사용하세요.");}
 private void admin(Invocation in){if(!in.source().hasPermission("customnickname.admin")){tell(in.source(),"권한이 없습니다.");return;}String[] a=in.arguments();if(a.length==0){tell(in.source(),"/닉관리 지급 <온라인계정명> | 강제변경 <대상> <새이름> <사유> | 기록 <대상> [페이지]");return;}String actor=in.source() instanceof Player p?p.getUniqueId().toString():"CONSOLE";if(eq(a[0],"지급","give")){if(a.length!=2)throw new IllegalArgumentException("/닉관리 지급 <온라인계정명>");Player target=proxy.getPlayer(a[1]).orElseThrow(()->new IllegalArgumentException("온라인 플레이어가 아닙니다."));finish(in.source(),names.issueTicket("ADMIN",actor,target.getUniqueId()),issue->{plugin.deliverTicket(target,issue);tell(in.source(),"변경권을 지급했습니다.");});return;}if(eq(a[0],"강제변경","set")){if(a.length<4)throw new IllegalArgumentException("/닉관리 강제변경 <대상> <새이름> <사유>");String reason=String.join(" ",Arrays.copyOfRange(a,3,a.length));finish(in.source(),resolve(a[1]).thenCompose(p->names.forceChange(p.playerId(),a[2],"ADMIN",actor,reason,UUID.randomUUID())),p->tell(in.source(),p.accountName()+" → "+p.nickname()));return;}if(eq(a[0],"기록","history")){if(a.length<2||a.length>3)throw new IllegalArgumentException("/닉관리 기록 <대상> [페이지]");int page=a.length==3?Integer.parseInt(a[2]):1;finish(in.source(),resolve(a[1]).thenCompose(p->names.history(p.playerId(),page)),entries->{tell(in.source(),"닉네임 기록 "+page+"페이지");for(HistoryEntry e:entries)tell(in.source(),"#"+e.id()+" "+e.oldName()+" → "+e.newName()+" | "+e.actorType()+":"+e.actorId()+" | "+e.reason());});return;}throw new IllegalArgumentException("/닉관리 지급 | 강제변경 | 기록");}
 private CompletableFuture<NicknameProfile> resolve(String value){UUID id=null;try{id=UUID.fromString(value);}catch(IllegalArgumentException ignored){}CompletableFuture<Optional<NicknameProfile>> result=id!=null?names.findById(id):value.startsWith("@")?names.findByAccountName(value.substring(1)):names.findByNickname(value);return result.thenApply(v->v.orElseThrow(()->new IllegalArgumentException("플레이어를 찾을 수 없습니다.")));}
 private void show(CommandSource source,NicknameProfile p){tell(source,p.nickname()+" / 계정명: "+p.accountName()+" / UUID: "+p.playerId());}
 private <T>void finish(CommandSource source,CompletableFuture<T> future,java.util.function.Consumer<T> success){future.whenComplete((value,error)->{if(error==null)success.accept(value);else{Throwable cause=VelocityNicknamePlugin.unwrap(error);if(!(cause instanceof IllegalArgumentException))logger.warn("명령 처리 실패",cause);tell(source,VelocityNicknamePlugin.safeMessage(cause));}});}
 private static boolean eq(String input,String a,String b){return input.equalsIgnoreCase(a)||input.equalsIgnoreCase(b);}
 private static void tell(CommandSource source,String text){source.sendMessage(Component.text("[닉네임] "+text));}
 @Override public boolean hasPermission(Invocation invocation){return !admin||invocation.source().hasPermission("customnickname.admin");}
 @Override public List<String> suggest(Invocation invocation){if(invocation.arguments().length!=1)return List.of();return (admin?List.of("지급","강제변경","기록"):List.of("조회","변경")).stream().filter(s->s.startsWith(invocation.arguments()[0])).toList();}
}
